name: Deploy a Hostinger

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Obtener cÃ³digo mÃ¡s reciente
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ðŸ“‚ Sincronizar archivos FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 195.35.33.109
          username: u947001429.gaboprueba
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: wp-content/themes/child-theme/
